// 05_shortest_path_binary_matrix.cpp — LeetCode 1091. Shortest Path in Binary Matrix (medium)
// 8-connected BFS; path length counts cells, so the start contributes 1.
#include <cassert>
#include <iostream>
#include <queue>
#include <utility>
#include <vector>

int shortestPathBinaryMatrix(std::vector<std::vector<int>>& grid) {
    const int n = static_cast<int>(grid.size());
    if (n == 0 || grid[0][0] != 0 || grid[n - 1][n - 1] != 0) return -1;
    std::vector<std::vector<int>> dist(n, std::vector<int>(n, 0));  // 0 = unvisited
    std::queue<std::pair<int, int>> q;
    dist[0][0] = 1;
    q.push({0, 0});
    while (!q.empty()) {
        auto [r, c] = q.front();
        q.pop();
        if (r == n - 1 && c == n - 1) return dist[r][c];  // first pop of the goal is optimal in BFS
        // All eight neighbours, generated by a double loop instead of a table.
        for (int dr = -1; dr <= 1; ++dr)
            for (int dc = -1; dc <= 1; ++dc) {
                if (dr == 0 && dc == 0) continue;
                const int nr = r + dr, nc = c + dc;
                if (nr < 0 || nr >= n || nc < 0 || nc >= n || grid[nr][nc] != 0 || dist[nr][nc] != 0) continue;
                dist[nr][nc] = dist[r][c] + 1;
                q.push({nr, nc});
            }
    }
    return -1;
}

int main() {
    {
        std::vector<std::vector<int>> g = {{0, 1}, {1, 0}};
        assert(shortestPathBinaryMatrix(g) == 2);  // one diagonal step
    }
    {
        std::vector<std::vector<int>> g = {{0, 0, 0}, {1, 1, 0}, {1, 1, 0}};
        assert(shortestPathBinaryMatrix(g) == 4);
    }
    {
        std::vector<std::vector<int>> g = {{1, 0, 0}, {1, 1, 0}, {1, 1, 0}};
        assert(shortestPathBinaryMatrix(g) == -1);  // start blocked
    }
    {
        std::vector<std::vector<int>> g = {{0}};
        assert(shortestPathBinaryMatrix(g) == 1);  // start == goal
    }
    {
        std::vector<std::vector<int>> g = {{0, 0, 0}, {0, 1, 0}, {0, 0, 0}};
        assert(shortestPathBinaryMatrix(g) == 4);  // around the centre: (0,0)(0,1)(1,2)(2,2) or mirror
    }
    std::cout << "OK 05_shortest_path_binary_matrix.cpp\n";
    return 0;
}
